# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "All Posts"
  url = "all_posts/"
  weight = 10

[[main]]
  name = "Global Health & Childhood Cancer"
  url = "ghcc/"
  weight = 20
  
[[main]]
  name = "Data Science + Global Health"
  url = "ds_gh/"
  weight = 30
  
[[main]]
  name = "Statistics & Heuristics"
  url = "statistics/"
  weight = 40

[[main]]
  name = "Confident Uncertainty"
  url = "misc/"
  weight = 50

[[main]]
  name = "GHCC Podcast"
  url = "https://www.ghccpod.com"
  weight = 60

[[main]]
  name = "POINTE"
  url = "https://www.cancerpointe.com"
  weight = 70


#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
